title: "Vanilla DI"
description: "A fast, lightweight, cross-platform Java Dependency Injection framework"
author: "Carlos Chacin"
author_url: "https://carloschac.in"
url: "https://vanilla-di.com"
baseurl: ""

# Environment-specific settings
# Force production URLs in all environments (development and production)
# This ensures SEO tags always use production URLs even in development
JEKYLL_ENV: production

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Production URL override for development
# This ensures consistent URLs in meta tags
production_url: "https://vanilla-di.com"

# Override environment to ensure production URLs in development
environment: production

# Exclude from processing
exclude:
  - README.md
  - JEKYLL_ENHANCEMENT_PLAN.md
  - CLAUDE.md
  - .gitignore
  - Gemfile
  - Gemfile.lock